# Generated by Django 3.2.8 on 2021-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='passwrd',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Uname',
            field=models.CharField(max_length=15),
        ),
    ]
