# Generated by Django 3.2.8 on 2021-10-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_shopping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='phone',
            field=models.IntegerField(verbose_name=15),
        ),
    ]
