# Generated by Django 3.2.8 on 2021-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_shopping_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='shopping',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
