# Generated by Django 3.2.8 on 2021-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211018_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=12, unique=True)),
                ('acc_holder', models.CharField(max_length=20)),
                ('atm', models.CharField(max_length=12)),
                ('cvv', models.CharField(max_length=4)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='shopping',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
