# Generated by Django 3.2.8 on 2021-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20211021_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_email', models.CharField(max_length=20, unique=True)),
                ('emp_ph', models.IntegerField()),
                ('emp_dept', models.CharField(max_length=20)),
                ('emp_username', models.CharField(max_length=20)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
    ]
