# Generated by Django 3.2.8 on 2021-11-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='pics',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
